package com.project.permis.entities;
// Generated 15 juin 2016 14:18:02 by Hibernate Tools 4.0.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Action generated by hbm2java
 */
public class Action implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set flags = new HashSet(0);
	private Set actionsForIdParent = new HashSet(0);
	private Set actionsForIdChild = new HashSet(0);
	private Set rules = new HashSet(0);
	private Set games = new HashSet(0);
	private Set studentActions = new HashSet(0);
	private Set goals = new HashSet(0);

	public Action() {
	}

	public Action(String name, Set flags, Set actionsForIdParent, Set actionsForIdChild, Set rules, Set games,
			Set studentActions, Set goals) {
		this.name = name;
		this.flags = flags;
		this.actionsForIdParent = actionsForIdParent;
		this.actionsForIdChild = actionsForIdChild;
		this.rules = rules;
		this.games = games;
		this.studentActions = studentActions;
		this.goals = goals;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getFlags() {
		return this.flags;
	}

	public void setFlags(Set flags) {
		this.flags = flags;
	}

	public Set getActionsForIdParent() {
		return this.actionsForIdParent;
	}

	public void setActionsForIdParent(Set actionsForIdParent) {
		this.actionsForIdParent = actionsForIdParent;
	}

	public Set getActionsForIdChild() {
		return this.actionsForIdChild;
	}

	public void setActionsForIdChild(Set actionsForIdChild) {
		this.actionsForIdChild = actionsForIdChild;
	}

	public Set getRules() {
		return this.rules;
	}

	public void setRules(Set rules) {
		this.rules = rules;
	}

	public Set getGames() {
		return this.games;
	}

	public void setGames(Set games) {
		this.games = games;
	}

	public Set getStudentActions() {
		return this.studentActions;
	}

	public void setStudentActions(Set studentActions) {
		this.studentActions = studentActions;
	}

	public Set getGoals() {
		return this.goals;
	}

	public void setGoals(Set goals) {
		this.goals = goals;
	}

}
