package com.project.permis.entities;
// Generated 15 juin 2016 14:18:02 by Hibernate Tools 4.0.0.Final

/**
 * Flag generated by hbm2java
 */
public class Flag implements java.io.Serializable {

	private Integer id;
	private Action action;
	private String description;
	private Integer value;

	public Flag() {
	}

	public Flag(Action action) {
		this.action = action;
	}

	public Flag(Action action, String description, Integer value) {
		this.action = action;
		this.description = description;
		this.value = value;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Action getAction() {
		return this.action;
	}

	public void setAction(Action action) {
		this.action = action;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getValue() {
		return this.value;
	}

	public void setValue(Integer value) {
		this.value = value;
	}

}
