package com.project.permis.entities;
// Generated 15 juin 2016 14:18:02 by Hibernate Tools 4.0.0.Final

/**
 * Message generated by hbm2java
 */
public class Message implements java.io.Serializable {

	private Integer id;
	private Student student;
	private String subject;
	private String body;

	public Message() {
	}

	public Message(Student student) {
		this.student = student;
	}

	public Message(Student student, String subject, String body) {
		this.student = student;
		this.subject = subject;
		this.body = body;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

}
