package com.project.permis.entities;
// Generated 19 juin 2016 15:18:34 by Hibernate Tools 4.0.0.Final

import java.util.Date;

/**
 * Message generated by hbm2java
 */
public class Message implements java.io.Serializable {

	private Integer id;
	private Student student;
	private String subject;
	private String body;
	private Boolean read;
	private Date dateReceipt;

	public Message() {
	}

	public Message(Student student) {
		this.student = student;
	}

	public Message(Student student, String subject, String body, Boolean read, Date dateReceipt) {
		this.student = student;
		this.subject = subject;
		this.body = body;
		this.read = read;
		this.dateReceipt = dateReceipt;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	public Boolean getRead() {
		return this.read;
	}

	public void setRead(Boolean read) {
		this.read = read;
	}

	public Date getDateReceipt() {
		return this.dateReceipt;
	}

	public void setDateReceipt(Date dateReceipt) {
		this.dateReceipt = dateReceipt;
	}

}
