package com.project.permis.entities;
// Generated 15 juin 2016 14:18:02 by Hibernate Tools 4.0.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Mission generated by hbm2java
 */
public class Mission implements java.io.Serializable {

	private Integer id;
	private String title;
	private Set games = new HashSet(0);
	private Set goals = new HashSet(0);

	public Mission() {
	}

	public Mission(String title, Set games, Set goals) {
		this.title = title;
		this.games = games;
		this.goals = goals;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Set getGames() {
		return this.games;
	}

	public void setGames(Set games) {
		this.games = games;
	}

	public Set getGoals() {
		return this.goals;
	}

	public void setGoals(Set goals) {
		this.goals = goals;
	}

}
