package com.project.permis.entities;
// Generated 18 juin 2016 09:54:13 by Hibernate Tools 4.0.0.Final

/**
 * StudentAction generated by hbm2java
 */
public class StudentAction implements java.io.Serializable {

	private StudentActionId id;
	private Action action;
	private Calendar calendar;
	private Student student;
	private Integer value;

	public StudentAction() {
	}

	public StudentAction(StudentActionId id, Action action, Calendar calendar, Student student) {
		this.id = id;
		this.action = action;
		this.calendar = calendar;
		this.student = student;
	}

	public StudentAction(StudentActionId id, Action action, Calendar calendar, Student student, Integer value) {
		this.id = id;
		this.action = action;
		this.calendar = calendar;
		this.student = student;
		this.value = value;
	}

	public StudentActionId getId() {
		return this.id;
	}

	public void setId(StudentActionId id) {
		this.id = id;
	}

	public Action getAction() {
		return this.action;
	}

	public void setAction(Action action) {
		this.action = action;
	}

	public Calendar getCalendar() {
		return this.calendar;
	}

	public void setCalendar(Calendar calendar) {
		this.calendar = calendar;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public Integer getValue() {
		return this.value;
	}

	public void setValue(Integer value) {
		this.value = value;
	}

}
