package com.project.permis.entities;
// Generated 26 juin 2016 14:31:07 by Hibernate Tools 4.0.0.Final

import java.util.Date;

/**
 * StudentActionId generated by hbm2java
 */
public class StudentActionId implements java.io.Serializable {

	private int idStudent;
	private int idAction;
	private Date date;

	public StudentActionId() {
	}

	public StudentActionId(int idStudent, int idAction, Date date) {
		this.idStudent = idStudent;
		this.idAction = idAction;
		this.date = date;
	}

	public int getIdStudent() {
		return this.idStudent;
	}

	public void setIdStudent(int idStudent) {
		this.idStudent = idStudent;
	}

	public int getIdAction() {
		return this.idAction;
	}

	public void setIdAction(int idAction) {
		this.idAction = idAction;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StudentActionId))
			return false;
		StudentActionId castOther = (StudentActionId) other;

		return (this.getIdStudent() == castOther.getIdStudent()) && (this.getIdAction() == castOther.getIdAction())
				&& ((this.getDate() == castOther.getDate()) || (this.getDate() != null && castOther.getDate() != null
						&& this.getDate().equals(castOther.getDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdStudent();
		result = 37 * result + this.getIdAction();
		result = 37 * result + (getDate() == null ? 0 : this.getDate().hashCode());
		return result;
	}

}
